# Basic set up for three package managers

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/CZ.AspNetCore.EasyAuthAuthentication" #CZ.AspNetCore.EasyAuthAuthentication.csproj
    schedule:
      interval: "weekly"
      day: "wednesday"
